version: '3.4'

services:
  server:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - $PWD:/app
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - db
    links:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    deploy:
      resources:
        limits:
          memory: 2500M
        reservations:
          cpus: '500M'
          memory: 100M


  proxy:
    build: dockerfiles/proxy
    env_file:
      - .env
    ports:
      - '5000:80'
    depends_on:
      - server
    links:
      - server

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
