version: '3.4'

services:
  server:
    build:
      context: .
      target: backend
    env_file:
      - .env
    ports:
      - '8000:8000'
      - '5678:5678'
    volumes:
      - $PWD:/app
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - db
    links:
      - db
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          cpus: '100M'
          memory: 100M

  proxy:
    build: dockerfiles/proxy
    env_file:
      - .env
    ports:
      - '5000:80'
    depends_on:
      - server
    links:
      - server

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
