# Generated by Django 3.1.13 on 2022-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usageinstrumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeBuildJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('probe_name', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('process', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'status_submitted'), ('STARTED', 'status_started'), ('FAILED', 'status_failed'), ('SUCCEEDED', 'status_succeeded')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
